[package]
name = "Guess_The_Number"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3"
rand = "0.8.3"
colored = "2"
